### ISSUE TITLE
Keyhunter in nettori access cheap shots you

### ISSUE THREAD

**Issue by Miepee** [MetroidAdvRandomizerSystem/MARS-Fusion#106]
It spawns somewhere here:
![grafik](https://github.com/user-attachments/assets/19d456e6-8eb0-4eb2-b7dd-0ff3054c9d4a)

but the camera doesnt let you see him, so when you shoot the top most blocks he either immediately jumps down on you, or you hit him while jumping up

**Comment by cluekitty** [comment]
I think this is supposed to be a flying Ki hunter. Looking in MAGE it's actually set to spawn inside of the vines. Perhaps the grounded Ki hunter AI will push it through walls if it's stuck in clipdata? It looks like antymew intentionally changed this Ki hunter so if we want it to spawn properly perhaps we just remove the clipdata around it instead of making it flying again

**Comment by Miepee** [comment]
This reminds me that I havent actually tested the position on the post nettori layer....
