### ISSUE TITLE
Disable arrows for area maps with no downloaded/explored tiles

### ISSUE THREAD

**Issue by biosp4rk** [MetroidAdvRandomizerSystem/MARS-Fusion#19]
![empty_map](https://github.com/MetroidAdvRandomizerSystem/MARS-Fusion/assets/37962487/1a02212e-e271-48e7-a78c-a7a7119026cf)

The map switching feature should probably skip maps that have no visible tiles because they aren't downloaded or explored. If it's worth showing empty maps for some reason, then perhaps the scroll arrows should be removed.

**Comment by AntyMew** [comment]
Is there an easy way to check if a sector has no explored tiles? I can't find one at a glance, it seems very expensive to check

**Comment by cluekitty** [comment]
Would it be easy to disable them via the "Downloaded Maps" RAM address? You start with your starting sector, and visiting a new sector "downloads" the map automatically. Would mean that the instant you enter a new sector, you automatically have the new map available because you would have visited at least 1 tile.

**Comment by AntyMew** [comment]
I suppose there isn't any reason to hide the minimap, considering you can just hit the nav room for it at any time. That's probably the best compromise

**Comment by Miepee** [comment]
IMO its better for muscle memory to never skip sectors. so to always have 1 -> 2 -> 3 -> 4 -> 5 ->6 -> Main Deck -> 1
Would be nice to get rid of the arrows tho.
